version: '3.3'
services:
  image1:
    image: nginx
    volumes:
    - ./index.html:/usr/share/nginx/html/index.html nginx
    ports:
    - 81:80
    networks:
      mgmnt:
        ipv4_address: "192.168.80.2"

  image2:
    image: nginx
    volumes:
    - ./2.html:/usr/share/nginx/html/index.html nginx
    ports:
    - 82:80
    networks:
      mgmnt:
        ipv4_address: "192.168.80.3"
  image3:
    image: nginx
    volumes:
    - ./3.html:/usr/share/nginx/html/index.html nginx
    ports:
    - 83:80
    networks:
      mgmnt:
        ipv4_address: "192.168.80.4"
  proxy:
    image: nginx
    volumes:
    - ./proxy.conf:/etc/nginx/conf.d/default.conf 
    ports:
    - 80:80
    networks:
      mgmnt:
        ipv4_address: "192.168.80.5"
networks:
  mgmnt:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/16
         gateway: 192.168.0.1