FROM ubuntu
WORKDIR /appNN
EXPOSE 8000
EXPOSE 3306
RUN apt-get update 
RUN apt-get install -y openjdk-17-jdk
RUN apt-get install -y curl
RUN apt-get install -y nano
ADD / /appNN
RUN curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt install nodejs
CMD ["npx","prisma migrate dev --name init"]